[workspace]
members = ["client", "server", "lib/types"]

[workspace.dependencies]
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
dotenv = "0.15"
envy = "0.4"
