/*
 Generated by typeshare 1.0.0
*/

/** GET VERSION */
export interface GetVersion {
}

export interface GetVersionResponse {
	version: string;
}

/** GET SERVER */
export interface GetServer {
	id: string;
}

export interface GetServerResponse {
	id: string;
}

export interface GetDeployment {
	id: string;
}

export interface GetDeploymentResponse {
	id: string;
}

/** GET BUILD */
export interface GetBuild {
	id: string;
}

export interface GetBuildResponse {
	id: string;
}

export interface Other {
}

export interface OtherResponse {
	other: string;
}

export interface Server {
	_id?: string;
	name: string;
	description: string;
}

export interface Deployment {
	_id?: string;
	name: string;
	description: string;
	server_id: string;
	image: DeploymentImage;
}

export type DeploymentImage = 
	| { type: "Build", id: string }
	| { type: "Custom", id: string };

export type Request = 
	| { type: "GetVersion", params: GetVersion }
	| { type: "GetServer", params: GetServer }
	| { type: "GetDeployment", params: GetDeployment }
	| { type: "GetBuild", params: GetBuild }
	| { type: "Other", params: Other };

