/*
 Generated by typeshare 1.0.0
*/

export interface GetVersion {
}

export interface GetVersionResponse {
	version: string;
}

export interface GetServer {
	id: string;
}

export interface GetDeployment {
	id: string;
}

export interface GetBuild {
	id: string;
}

export interface Server {
	_id?: string;
	name: string;
	description: string;
}

export interface Deployment {
	_id?: string;
	name: string;
	description: string;
	server_id: string;
	image: DeploymentImage;
}

export type Request = 
	| { type: "GetVersion", params?: undefined }
	| { type: "GetServer", params: GetServer }
	| { type: "GetDeployment", params: GetDeployment }
	| { type: "GetBuild", params: GetBuild };

export type DeploymentImage = 
	| { type: "Build", id: string }
	| { type: "Custom", id: string };

