/*
 Generated by typeshare 1.0.0
*/

export interface Id {
	id: string;
}

export interface GetVersion {
	version: string;
}

export interface GetServer {
}

export interface GetDeployment {
}

export interface Server {
	_id?: string;
	name: string;
	description: string;
}

export interface Deployment {
	_id?: string;
	name: string;
	description: string;
	server_id: string;
	image: DeploymentImage;
}

export type Request = 
	| { type: "GetVersion", params?: undefined }
	| { type: "GetServer", params: Id }
	| { type: "GetDeployment", params: Id };

export type DeploymentImage = 
	| { type: "Build", id: string }
	| { type: "Custom", id: string };

